### ISSUE TITLE
Fix SAM function

### ISSUE THREAD

**Issue by akshathmangudi** [akshathmangudi/rgb-to-hyper#1]
## COMMIT #15

Refer to more details inside the `review` sub-section of the server.

**Comment by harshithasudhakar** [comment]
@rhrithik Will be looking into it.

**Comment by harshithasudhakar** [comment]
@akshathmangudi Has fixed the logging

**Comment by akshathmangudi** [comment]
UPDATE: Problem has been fixed, refer to latest commit. Closing the issue now.
