### ISSUE TITLE
Fix HSI - RGB Mapping & Augmentation

### ISSUE THREAD

**Issue by harshithasudhakar** [akshathmangudi/rgb-to-hyper#6]
Priority: URGENT

**Comment by akshathmangudi** [comment]
[DUPLICATE OF ISSUE #3] 

marking this as closed.

**Comment by harshithasudhakar** [comment]
Also need to fix augmentation.
The original HSIs are laterally flipped
![WhatsApp Image 2024-11-02 at 17 52 27_8e62f26f](https://github.com/user-attachments/assets/09255554-312c-448e-be68-f2da902a5a97)

**Comment by akshathmangudi** [comment]
it's in the same orientation, recheck once with the new commit and let me know @harshithasudhakar

**Comment by harshithasudhakar** [comment]
yeah, my local clone was outdated. works now :)
