### ISSUE TITLE
`unet_main.py` not generating HSI

### ISSUE THREAD

**Issue by harshithasudhakar** [akshathmangudi/rgb-to-hyper#9]
`unet_main.py` is supposed to generate the HSI images in `gen_hsi`, it doesn't seem to be working though.

**Comment by akshathmangudi** [comment]
closing this issue as it's resolved in some other file. refer to `unet.py`

**Comment by harshithasudhakar** [comment]
Doesn't generate the images well

**Comment by harshithasudhakar** [comment]
Generates the images well.

![WhatsApp Image 2024-11-20 at 02 19 39_3ef4dda4](https://github.com/user-attachments/assets/e27341d4-5709-4690-94d1-af76f735bbbd)

**At EPOCH 2**
